DROP DATABASE IF EXISTS rest_api_db;
CREATE DATABASE rest_api_db;
USE rest_api_db;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
	ID_USER INT NOT NULL AUTO_INCREMENT,
	LOGIN VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	GENDER VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID_USER)
);

DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE (
	ID_ROLE INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID_ROLE)
);

DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE (
	ID_USER_ROLE INT NOT NULL AUTO_INCREMENT,
	ID_USER INT NOT NULL,
	ID_ROLE INT NOT NULL,
	PRIMARY KEY (ID_USER_ROLE),
    CONSTRAINT fk_user
		FOREIGN KEY (ID_USER)
		REFERENCES USER(ID_USER),
    CONSTRAINT fk_role
		FOREIGN KEY (ID_ROLE)
		REFERENCES ROLE(ID_ROLE)
);

INSERT INTO ROLE (ID_ROLE, NAME)
	VALUES
	(1, "ADMIN"),
	(2, "MODERATOR"),
	(3, "REGULAR_USER");

INSERT INTO USER (ID_USER, LOGIN, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, GENDER)
	VALUES
	(1, "admin", "admin", "admin@api.com", "admin", "admin", "Unown"),
	(2, "moderator", "moderator", "moderator@api.com", "moderator", "moderator", "Unown"),
	(3, "regular_user", "regular_user", "regular_user@api.com", "regular_user", "regular_user", "Unown");

INSERT INTO USER_ROLE (ID_USER_ROLE, ID_USER, ID_ROLE)
	VALUES
	(1, 1, 1),
	(2, 2, 2),
	(3, 3, 3);